USE MASTER 
GO

CREATE DATABASE QUANLYBANQUANAO
GO

USE QUANLYBANQUANAO
GO

CREATE TABLE SANPHAM(
	ID INT IDENTITY(1,1),
	TEN NVARCHAR(255),
	PRIMARY KEY(ID)
)

GO

CREATE TABLE SIZE(
	ID INT IDENTITY(1,1),
	TEN NVARCHAR(255),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE NSX(
	ID INT IDENTITY(1,1),
	TEN NVARCHAR(255),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE DONGSP(
	ID INT IDENTITY(1,1),
	TEN NVARCHAR(255),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE MAUSAC(
	ID INT IDENTITY(1,1),
	TEN NVARCHAR(255),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE CHATLIEU(
	ID INT IDENTITY(1,1),
	TEN NVARCHAR(255),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE CHITIETSP(
	ID INT IDENTITY(1,1),
	IDSP INT,
	IDDONGSP INT,
	IDMAUSAC INT,
	IDCHATLIEU INT,
	IDSIZE INT,
	IDNSX INT,
	ANH NVARCHAR(255),
	SOLUONGTON INT,
	GIA INT,
	MAVACH INT,
	MOTA NVARCHAR(255),
	PRIMARY KEY(ID),
	FOREIGN KEY(IDSP) REFERENCES SANPHAM(ID),
	FOREIGN KEY(IDDONGSP) REFERENCES DONGSP(ID),
	FOREIGN KEY(IDMAUSAC) REFERENCES MAUSAC(ID),
	FOREIGN KEY(IDCHATLIEU) REFERENCES CHATLIEU(ID),
	FOREIGN KEY(IDSIZE) REFERENCES SIZE(ID),
	FOREIGN KEY(IDNSX) REFERENCES NSX(ID)
)
GO

CREATE TABLE CHUCVU(
	ID INT IDENTITY(1,1),
	TEN NVARCHAR(255),
	PRIMARY KEY(ID)
)
GO

CREATE TABLE NHANVIEN(
	ID INT IDENTITY(1,1),
	MANV NVARCHAR(20) UNIQUE,
	TEN NVARCHAR(255),
	IDCHUCVU INT,
	GIOITINH BIT,
	NGAYSINH DATE,
	SDT NVARCHAR(10) UNIQUE NOT NULL,
	DIACHI NVARCHAR(255),
	EMAIL NVARCHAR(255) UNIQUE NOT NULL,
	MATKHAU NVARCHAR(255),
	TRANGTHAI BIT,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDCHUCVU) REFERENCES CHUCVU(ID)
)
GO

CREATE TABLE KHUYENMAI(
	ID INT IDENTITY(1,1),
	MAKHUYENMAI NVARCHAR(20) UNIQUE,
	TEN NVARCHAR(255),
	MUCGIAMGIA INT,
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE,
	PRIMARY KEY(ID)
)
GO


CREATE TABLE KHACHHANG(
	ID INT IDENTITY(1,1),
	TEN NVARCHAR(255),
	SDT NVARCHAR(10),
	EMAIL NVARCHAR(255),
	CAPBAC INT DEFAULT 0,
	DIACHI NVARCHAR(255),
	PRIMARY KEY(ID)
)
GO 
CREATE TABLE HOADON(
	ID INT IDENTITY(1,1),
	IDNHANVIEN INT,
	IDKHACHHANG INT,
	SDT NVARCHAR(10),
	DIACHI NVARCHAR(255),
	HINHTHUCGIAOHANG INT DEFAULT 0,
	HINHTHUCTHANHTOAN INT DEFAULT 0,
	LYDO NVARCHAR(255),
	NGAYSHIP DATE,
	NGAYTHANHTOAN DATE,
	TIENKHACHTRA INT DEFAULT 0,
	TIENKHACHCHUYENKHOAN INT DEFAULT 0,
	NGAYTAO DATE,
	TRANGTHAI INT DEFAULT 0,
	TONGTIEN INT DEFAULT 0,
	IDKHUYENMAI INT,
	TIENSAUGIAMGIA INT,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDNHANVIEN) REFERENCES NHANVIEN(ID),
	FOREIGN KEY(IDKHUYENMAI) REFERENCES KHUYENMAI(ID),
	FOREIGN KEY(IDKHACHHANG) REFERENCES KHACHHANG(ID)
)
GO

CREATE TABLE HOADONCHITIET(
	ID INT IDENTITY(1,1),
	IDHOADON INT,
	IDCTSP INT,
	TENSP NVARCHAR(255),
	TENNSX NVARCHAR(255),
	DONGSP NVARCHAR(255),
	MAUSAC NVARCHAR(255),
	ANH NVARCHAR(255),
	SIZE NVARCHAR(255),
	SOLUONG INT,
	DONGIA INT,
	PRIMARY KEY(ID),
	FOREIGN KEY(IDHOADON) REFERENCES HOADON(ID),
	FOREIGN KEY(IDCTSP) REFERENCES CHITIETSP(ID)
)
GO

INSERT INTO SANPHAM VALUES(N'Áo cụt cánh')
INSERT INTO SANPHAM VALUES(N'Quần đùi')
INSERT INTO SANPHAM VALUES(N'Áo sơ mi')
INSERT INTO NSX VALUES('NSX1')
INSERT INTO NSX VALUES('NSX2')
INSERT INTO NSX VALUES('NSX3')
INSERT INTO SIZE VALUES('S')
INSERT INTO SIZE VALUES('L')
INSERT INTO SIZE VALUES('XL')
INSERT INTO SIZE VALUES('XXL')
INSERT INTO MAUSAC VALUES(N'Xanh')
INSERT INTO MAUSAC VALUES(N'Đỏ')
INSERT INTO MAUSAC VALUES(N'Vàng')
INSERT INTO DONGSP VALUES(N'Áo')
INSERT INTO DONGSP VALUES(N'Quần')













--CREATE TABLE CALAM(
	
--)



--USE MASTER
--GO
--DROP DATABASE QUANLYBANQUANAO
