/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.it17326.group3.view;

import com.poly.it17326.group3.domainmodels.HoaDonChiTiet;
import com.poly.it17326.group3.repository.HoaDonChiTietReposity;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author doand
 */
public class FrmHoaDonChiTiet extends javax.swing.JPanel {
    HoaDonChiTietReposity hoaDonChiTietReposity = new HoaDonChiTietReposity();
    /**
     * Creates new form HoaDonChiTiet
     */
    
    public void loadTable(ArrayList<HoaDonChiTiet> list) {
        DefaultTableModel model = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        model.setRowCount(0);

        model.setColumnIdentifiers(new Object[]{
          "Ma Sp" ,"Ten Sp" ,"so luong","don gia" ,"Thanh tien"
        });
        
        for (HoaDonChiTiet hoaDonChiTiet : list) {
            Object[] row = new Object[]{
                hoaDonChiTiet.getIdHoaDonCT(),hoaDonChiTiet.getTenSp(),hoaDonChiTiet.getSoLuong(),hoaDonChiTiet.getDONGIA(),hoaDonChiTiet.getSoLuong()*hoaDonChiTiet.getDONGIA()
            };
            model.addRow(row);
        }
        
    }
    public FrmHoaDonChiTiet() {
        initComponents();
        loadTable(hoaDonChiTietReposity.getAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHoaDonChiTiet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDonChiTiet;
    // End of variables declaration//GEN-END:variables
}
