/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.it17326.group3.view;

import com.poly.it17326.group3.domainmodels.HoaDon;
import com.poly.it17326.group3.domainmodels.NhanVien;
import com.poly.it17326.group3.repository.HoaDonReposity;
import java.awt.JobAttributes;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author doand
 */
public class FrmHoaDon extends javax.swing.JPanel {

    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private HoaDonReposity hoaDonReposity = new HoaDonReposity();

    /**
     * Creates new form FrmHoaDon
     */
    public void loadHoaDon(ArrayList<HoaDon> list) {
        DefaultTableModel model = (DefaultTableModel) tblTaoHoaDOn.getModel();
        model.setNumRows(0);

        model.setColumnIdentifiers(new Object[]{
            "ma hoa don", "ngay tao", "ngay thanh toan", "nhan vien tao", "khach hang"
        });

        for (HoaDon hoaDon : list) {
            Object[] row = new Object[]{
                hoaDon.getId(), hoaDon.getNgayTao(), hoaDon.getNgayThanhToan(),hoaDon.getNhanVien().getTenNhanVien(), hoaDon.getTenKhachHang()
            };
            model.addRow(row);
        }

    }

    public FrmHoaDon() {
        initComponents();
            loadHoaDon(hoaDonReposity.getAll());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaoHoaDOn = new javax.swing.JTable();

        jButton1.setText("Tao Hoa Don");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblTaoHoaDOn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTaoHoaDOn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HoaDon hd = new HoaDon();
        long millis = System.currentTimeMillis();
        java.sql.Date date = new java.sql.Date(millis);
        hd.setNgayTao(date);
        NhanVien nv = new NhanVien();
        nv.setId(1);
        hd.setNhanVien(nv);
        hd.setTenKhachHang("thien");
        if (hoaDonReposity.add(hd) == true) {
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTaoHoaDOn;
    // End of variables declaration//GEN-END:variables
}
